### PR TITLE
Update wmemu.c

### PR DESCRIPTION
**Pull request by mariob0y**

### CODE REVIEW

**Comment by JRogaishio** [comment]
@mariob0y I saw your email but I'm replying here so it's available to anyone else having similar issues.

You asked:

> I tried to build an emulator on my Dell Latitude 5520 laptop, running Ubuntu. 
> Even with your proposed fixes, it still failed with errors. Thus I tried to fix it: 
> https://github.com/JRogaishio/WiimoteEmulator/pull/1
> Full disclaimer: I never wrote anything on C or for Wii, so my PR probably makes little sense
>
> After that, I am able to successfully built an emulator, but I am unable to start it (even with sudo): 
> Since there is very little context about this emulator, I thought to ask you about it 
> 
> 1. Is it a problem with laptop bluetooth device? Should I buy a USB dongle with a mutable MAC-address?
> 2. Since I see RaspberryPi screenshots - is this emulator developed solely for RPI? Are my attempts to run it on a laptop futile? 
> 3. Is there any point to building an emulator, instead of just sharing releases of it? Let's say, if you share your build, from your machine - would it work for me? 

1. Yes the "Unsupported Manufacturer" means the Bluetooth device is not supported. 
I have the same issue for my main computer running Linux Mint 20.2 (Aka ubuntu 20.04) with an Intel bluetooth chipset.
    
2. I'm not 100% sure if it is developed solely for a RPi but I can confirm that a Raspberry Pi 4b does work as expected. 
See the below website which details all the various bluetooth devices that work with a Wii. Maybe you can find a usb dongle that is on that list so you don't need a RPi?
http://wiibrew.org/wiki/List_of_Working_Bluetooth_Devices
    
3. In theory if we're both on "Debian Linux" then a build should work across devices however I also never got a connection working from Ubuntu. I only got a Raspberry Pi working (because I don't have any spare Bluetooth dongles to test). To share builds on this Github repo I'd need to make a build for Debian Linux and a separate build for a RPi. No idea if I'd also need to make 20.04, 22.04, ... separate builds.

Full disclaimer for myself: I am also a C / Wii novice so most of my fixes were just playing around to see what works.

**Comment by mariob0y** [comment]
@JRogaishio thanks for your reply and insight! 

Maybe this info will be helpful to you as well. 
I tried different set of commands, based on this [bricked console ressurection guide ](https://gbatemp.net/threads/fix-ssl-module-brick-without-a-nand-backup-using-bluubomb.603510/), and it worked on my laptop, despite statement that my device isn't supported. Maybe it will work on your machine as well! 

Here is chuck of output as proof: 
```bash
Unsupported manufacturer
Failed to set device address
Device manufacturer: Intel Corp. (2)
Failed to set device address
Warning: device address must have a Nintendo OUI
Can't write simple pairing mode: Input/output error (5)
Failed to set simple pairing mode
Warning: make sure secure simple pairing mode is disabled
listening for connections... (press wii's sync button)
connected to 18:2A:7B:FA:31:E0
                           Reporting 0x30 (core buttons)
1704464866.863985     Wii: 17 00 00 17 70 00 01 (read eeprom)
1704464866.863998 Wiimote: 21 00 00 f8 17 70 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 (memory output)
1704464866.873878     Wii: 16 04 a4 00 f0 01 aa 7b 08 00 00 00 0f 10 02 7b 18 00 00 00 01 10 (write ext register a4)
1704464866.883944     Wii: 17 04 a6 00 f0 00 10 (read wmp register a6)
1704464866.893902     Wii: 1a 02 00 (set ir cam enable 0)
1704464866.903931     Wii: 11 (set player leds 0 1 0 0)
1704464866.913896     Wii: 17 00 00 00 2a 00 38 (read eeprom)
1704464866.930160     Wii: 17 00 00 00 62 00 38 (read eeprom)
1704464866.944015     Wii: 17 00 00 00 00 00 2a (read eeprom)
1704464866.960195     Wii: 15 (status request)
1704464866.975179     Wii: 12 (set reporting mode 30, cont: 1)
...
```

I've wrote down these command to a guide and added it to `/docs` folder.


> 1. Install dependencies:
> ```bash
> sudo apt install build-essential libbluetooth-dev libglib2.0-dev libdbus-1-dev git
> ```
> 2. Clone repo:
> ```bash
> git clone https://github.com/mariob0y/WiimoteEmulator && cd WiimoteEmulator
> ```
> 3. Build emulator:
> ```bash
> source ./build-custom.sh
> ```
> 3. Stop the already running bluetooth service:
> ```bash
> sudo systemctl disable --now bluetooth
> ```
> 4. Reboot.
> 5. Run:
> ```bash
> sudo hciconfig hci0 reset
> ```
> 6. Run:
> ```bash
> cd WiimoteEmulator && sudo ./bluez-4.101/dist/sbin/bluetoothd -d -n
> ```
> 7. In second terminal tab run:
> ```bash
> cd WiimoteEmulator && sudo ./wmemulator
> ```
>

**Comment by Groupix05** [comment]
Thanks @mariob0y, your code and commands are working perfectly on my Debian Linux. I can now connect my computer to the Wii.

**Comment by JRogaishio** [comment]
Thanks @Groupix05 for confirming these changes. I completely forgot about this pr. Merging now.

**Pull request merged**
